version: "3.8"

services:
  frontend:
    container_name: zameen-visit-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_URL=value
    command: npm run dev
